# Generated by Django 4.2 on 2023-11-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20190630_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("S", "Shirt"),
                    ("SW", "Sport wear"),
                    ("OW", "Outwear"),
                    ("A", "Accessories"),
                ],
                max_length=2,
            ),
        ),
    ]
